#spring:
#  application:
#    name: spring-cloud-nacos
#  cloud:
#    nacos:
      # service discovery
#      discovery:
#        server-addr: 127.0.0.1:8848
#feign:
#  client:
#    config:
#      spring-cloud-customer:
#        loggerLevel: full