spring:
  application:
    name: spring-cloud-config-client
  config:
    import: optional:configserver:http://127.0.0.1:8080
  cloud:
    config:
      enabled: true
      # not sure about this property.
      import-check:
        enabled: false
#      label: master # branch
      # spring profile, including postfix, such as *-dev.properties
#      profile: dev
      # configuration file name
      # this name is just for easy-to-remember.
      name: spring-cloud-client-config
      # use this "uri" when service registry is unavailable.
#      uri: http://127.0.0.1:8080
      discovery:
        enabled: true
        service-id: spring-cloud-config-server # seems like this doesn't work.
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8971/eureka

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: refresh,prometheus